version: 2
registries:
  github-releases:
    type: 'git'
    url: 'https://github.com'
    username: '${{ secrets.ACTOR }}'
    password: '${{ secrets.TOKEN }}'
updates:
  - package-ecosystem: 'gradle'
    directory: '/'
    schedule:
      interval: 'weekly'
    registries:
      - github-releases
  - package-ecosystem: 'gradle'
    directory: '/app'
    schedule:
      interval: 'weekly'
    with:
      gradle-version: '8.11.1'
