version: 2
registries:
  github-releases:
    type: 'git'
    url: 'https://github.com/Donnnno/candybar-foss/releases'
updates:
  - package-ecosystem: 'gradle'
    directory: '/'
    schedule:
      interval: 'weekly'
    registries:
      - github-releases
  - package-ecosystem: 'gradle'
    directory: '/app'
    schedule:
      interval: 'weekly'
