apply plugin: 'com.android.application'

android {
    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }
    compileSdk = rootProject.ext.CompileSdk

    defaultConfig {
        applicationId 'com.froxot.cuscon'
        minSdkVersion rootProject.ext.MinSdk
        targetSdkVersion rootProject.ext.TargetSdk
        versionCode 4113
        versionName '4.1.1.3'
        multiDexEnabled true
    }

    bundle {
        language { enableSplit false }
        density { enableSplit true }
    }

    signingConfigs {
        release {
            storeFile file("upload-keystore.jks")
            storePassword findProperty("PASSWORD")
            keyAlias 'upload'
            keyPassword findProperty("PASSWORD")
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    lint {
        abortOnError false
    }
    
    flavorDimensions "variant"
	productFlavors {
		play {
			dimension "variant"
			resValue "string", "app_name", "cuscon"
			matchingFallbacks = ["play"]
		}
		foss {
			dimension "variant"
			applicationIdSuffix '.foss'
			resValue "string", "app_name", "cuscon"
			matchingFallbacks = ["foss"]
		}
	}
    namespace 'com.froxot.cuscon'
}

base {
    archivesName = "${parent.name}-v${android.defaultConfig.versionCode}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
	playImplementation 'com.github.MiepHD.candybar:library:3.23.0.7'
	fossImplementation 'com.github.MiepHD:candybar-foss:3.23.0.7'
}

tasks.register('finishXMLs', Exec) {
    commandLine 'bash', './finishXMLs.sh'
}

tasks.register('generatedpis', Exec) {
    commandLine 'python3', './generatedpis.py'
}

// Erzwinge, dass die Build-Tasks erst NACH finishXMLs laufen
['assembleFossRelease', 'bundlePlayRelease', 'assemblePlayRelease'].each { taskName ->
    tasks.matching { it.name == taskName }.configureEach {
        mustRunAfter 'finishXMLs', 'clean'
    }
}

tasks.register('buildRelease') {
    dependsOn 'clean', 'finishXMLs', 'assembleFossRelease', 'bundlePlayRelease'
}
